### ISSUE TITLE
Need to figure out how (or if) to include scientific publications in resume

### ISSUE THREAD

**Issue by LeannaRM** [LeannaRM/growth#1]

**Comment by LeannaRM** [comment]
I published 2 scientific paper in peer-reviewed journals while getting my PhD and 1 since then. In the science world publications hold A LOT of weight when applying for jobs. So, it feels strange to me to leave them off completely, but I'm not really sure how to include them.

**Comment by LeannaRM** [comment]
Wondering if you have any thoughts or advice on this.

**Comment by sumeetjain** [comment]
I'm inclined to think they won't carry much weight in this industry. Their primary value in this context might be for expressing credibility, so mentioning that you "published papers in high impact, peer-reviewed journals" (or something brief, like that) under the heading for your PhD would be my advice.

**Comment by sumeetjain** [comment]
I think you'd also asked about Matlab? I'd put that under the Skills section, along w/ other skills from this class.
